!function(e) {
    function t(t) {
        for (var n, s, i = t[0], c = t[1], r = t[2], m = 0, d = []; m < i.length; m++)
            s = i[m],
            Object.prototype.hasOwnProperty.call(a, s) && a[s] && d.push(a[s][0]),
            a[s] = 0;
        for (n in c)
            Object.prototype.hasOwnProperty.call(c, n) && (e[n] = c[n]);
        for (g && g(t); d.length; )
            d.shift()();
        return p.push.apply(p, r || []),
        o()
    }
    function o() {
        for (var e, t = 0; t < p.length; t++) {
            for (var o = p[t], n = !0, s = 1; s < o.length; s++) {
                var c = o[s];
                0 !== a[c] && (n = !1)
            }
            n && (p.splice(t--, 1),
            e = i(i.s = o[0]))
        }
        return e
    }
    var n = {}
      , s = {
        233: 0
    }
      , a = {
        233: 0
    }
      , p = [];
    function i(t) {
        if (n[t])
            return n[t].exports;
        var o = n[t] = {
            i: t,
            l: !1,
            exports: {}
        };
        console.log(t)
        return e[t].call(o.exports, o, o.exports, i),
        o.l = !0,
        o.exports
    }
    i.e = function(e) {
        var t = []
          , o = function() {
            try {
                return document.createElement("link").relList.supports("preload")
            } catch (e) {
                return !1
            }
        }()
          , n = !1;
        s[e] ? t.push(s[e]) : 0 !== s[e] && {
            0: 1,
            1: 1,
            2: 1,
            3: 1,
            4: 1,
            5: 1,
            6: 1,
            7: 1,
            8: 1,
            9: 1,
            10: 1,
            11: 1,
            12: 1,
            14: 1,
            15: 1,
            16: 1,
            17: 1,
            18: 1,
            19: 1,
            20: 1,
            21: 1,
            22: 1,
            23: 1,
            24: 1,
            25: 1,
            26: 1,
            27: 1,
            28: 1,
            29: 1,
            30: 1,
            31: 1,
            32: 1,
            33: 1,
            34: 1,
            35: 1,
            36: 1,
            37: 1,
            39: 1,
            41: 1,
            42: 1,
            43: 1,
            44: 1,
            45: 1,
            46: 1,
            47: 1,
            48: 1,
            49: 1,
            50: 1,
            54: 1,
            55: 1,
            57: 1,
            58: 1,
            59: 1,
            60: 1,
            61: 1,
            62: 1,
            63: 1,
            64: 1,
            66: 1,
            67: 1,
            68: 1,
            69: 1,
            72: 1,
            73: 1,
            74: 1,
            75: 1,
            76: 1,
            77: 1,
            78: 1,
            81: 1,
            82: 1,
            83: 1,
            84: 1,
            85: 1,
            86: 1,
            87: 1,
            88: 1,
            89: 1,
            90: 1,
            91: 1,
            92: 1,
            93: 1,
            94: 1,
            95: 1,
            96: 1,
            97: 1,
            98: 1,
            99: 1,
            100: 1,
            101: 1,
            102: 1,
            104: 1,
            106: 1,
            108: 1,
            109: 1,
            110: 1,
            111: 1,
            112: 1,
            113: 1,
            114: 1,
            115: 1,
            116: 1,
            117: 1,
            118: 1,
            120: 1,
            121: 1,
            122: 1,
            123: 1,
            124: 1,
            125: 1,
            126: 1,
            127: 1,
            128: 1,
            129: 1,
            130: 1,
            131: 1,
            133: 1,
            134: 1,
            135: 1,
            136: 1,
            137: 1,
            138: 1,
            139: 1,
            140: 1,
            141: 1,
            142: 1,
            143: 1,
            144: 1,
            145: 1,
            146: 1,
            147: 1,
            148: 1,
            149: 1,
            150: 1,
            151: 1,
            152: 1,
            153: 1,
            154: 1,
            155: 1,
            156: 1,
            157: 1,
            158: 1,
            159: 1,
            160: 1,
            161: 1,
            162: 1,
            163: 1,
            164: 1,
            165: 1,
            166: 1,
            167: 1,
            169: 1,
            170: 1,
            171: 1,
            172: 1,
            173: 1,
            174: 1,
            175: 1,
            176: 1,
            177: 1,
            178: 1,
            179: 1,
            180: 1,
            181: 1,
            182: 1,
            183: 1,
            184: 1,
            185: 1,
            186: 1,
            187: 1,
            188: 1,
            189: 1,
            190: 1,
            191: 1,
            192: 1,
            193: 1,
            194: 1,
            195: 1,
            196: 1,
            197: 1,
            198: 1,
            199: 1,
            200: 1,
            201: 1,
            202: 1,
            203: 1,
            204: 1,
            206: 1,
            207: 1,
            208: 1,
            209: 1,
            210: 1,
            211: 1,
            212: 1,
            213: 1,
            214: 1,
            215: 1,
            216: 1,
            217: 1,
            218: 1,
            219: 1,
            220: 1,
            221: 1,
            222: 1,
            224: 1,
            225: 1,
            226: 1,
            227: 1,
            228: 1,
            229: 1,
            230: 1,
            231: 1,
            232: 1
        }[e] && t.push(s[e] = new Promise((function(t, a) {
            for (var p = ({
                0: "pages/reviews/components/ReviewsImgDialog",
                1: "pages/activity/components/ActivityProduct",
                2: "components/quick-pay",
                3: "components/lq-address-form",
                4: "components/design-components-components-normal-card",
                5: "components/redeem-product",
                6: "pages/activity/new-arrivals-pop-up/pages/contact-us/pages/retail-stores/index/pages/share-active/pag/1236ca99",
                7: "pages/blog/components/BlogLeft",
                8: "pages/activity/components/ImgClip",
                9: "pages/customer/order/return/components/order-detail",
                10: "pages/qa/components/QaItem",
                11: "components/pay",
                12: "pages/blog/components/BlogItem",
                13: "commons/pages/activity/new-user/pages/activity/play-claw-machine",
                14: "components/canle-order",
                15: "components/design-components-banner",
                16: "components/design-components-bannerts",
                17: "components/design-components-barrages",
                18: "components/design-components-button",
                19: "components/design-components-carousel",
                20: "components/design-components-comment",
                21: "components/design-components-components-flash-sale-card-amount",
                22: "components/design-components-components-flash-sale-card-discount",
                23: "components/design-components-components-four-product-swiper",
                24: "components/design-components-components-option-card",
                25: "components/design-components-components-points-card",
                26: "components/design-components-components-stock-card",
                27: "components/design-components-count-diy",
                28: "components/design-components-coupon",
                29: "components/design-components-cutdowns",
                30: "components/design-components-elevator-nav",
                31: "components/design-components-flash-sale-everyday",
                32: "components/design-components-goods-list",
                33: "components/design-components-goods-list-tab",
                34: "components/design-components-image-text",
                35: "components/design-components-morevideos",
                36: "components/design-components-questions",
                37: "components/design-components-recommend-list",
                38: "components/design-components-rich-text",
                39: "components/design-components-share",
                40: "components/design-components-title",
                41: "components/design-components-videos",
                42: "components/order-detail",
                43: "components/point-redeem-coupon",
                44: "components/product-how-to",
                45: "components/product-list-filter",
                46: "components/user-product-list",
                47: "pages/activity/unice-8th-anniversary-saving-guide/pages/index",
                48: "pages/cart/GatherProduct",
                49: "pages/customer/order/return/components/Refund",
                50: "pages/order/components/GiveUp",
                53: "components/billing-note",
                54: "components/bottom-img-list",
                55: "components/bread-crumb",
                56: "components/broken-skeleton",
                57: "components/chat-line",
                58: "components/cms-page",
                59: "components/coupon-pop",
                60: "components/el-select",
                61: "components/faq",
                62: "components/five-star",
                63: "components/head-title",
                64: "components/home-flash",
                65: "components/img-upload",
                66: "components/ios-btn",
                67: "components/loading-animationpage",
                68: "components/loading-start",
                69: "components/lq-check-box",
                70: "components/lq-track-detail",
                71: "components/lqwallet",
                72: "components/min-cart-item",
                73: "components/multi-select-button",
                74: "components/need-help",
                75: "components/order-coupon-item",
                76: "components/order-use-address",
                77: "components/order-use-coupon-p-c",
                78: "components/order-use-email",
                79: "components/order-use-pay-methods",
                80: "components/order-use-point",
                81: "components/pagenation",
                82: "components/pop-thrid-login-coupon",
                83: "components/product-card",
                84: "components/product-detail",
                85: "components/product-detail-estimated-price",
                86: "components/product-detail-interests",
                87: "components/product-gift",
                88: "components/product-how-to-item",
                89: "components/product-image",
                90: "components/product-list",
                91: "components/product-top",
                92: "components/radio-button-item",
                93: "components/review-filter",
                94: "components/select-option",
                95: "components/service",
                96: "components/sitejabber-no",
                97: "components/slide-bottom-dialog",
                98: "components/slide-middle-dialog",
                99: "components/slide-right-dialog",
                100: "components/slide-top-dialog",
                101: "components/swiper-diy",
                102: "components/tab-recommend-product",
                103: "components/third-login-icon",
                104: "components/topic-photo",
                105: "pages/403",
                106: "pages/404",
                107: "pages/_",
                108: "pages/activity/_",
                109: "pages/activity/back-to-school",
                110: "pages/activity/bargain/index",
                111: "pages/activity/black-friday-sale",
                112: "pages/activity/black-friday-shopping-guide",
                113: "pages/activity/check-in-get-rewards",
                114: "pages/activity/components/ActivityPointRedeemCoupon",
                115: "pages/activity/components/ActivityPointRedeemProduct",
                116: "pages/activity/components/BarrageSwiper",
                117: "pages/activity/components/GiftCardRecommendProduct",
                118: "pages/activity/components/PrizeWheelDialog",
                119: "pages/activity/components/Upload",
                120: "pages/activity/components/UploadImgVideo",
                121: "pages/activity/customer-photo-gallery",
                122: "pages/activity/customerreview",
                123: "pages/activity/every-day-flash",
                124: "pages/activity/halloween",
                125: "pages/activity/how-to-get-free-hair-and-cash-reward",
                126: "pages/activity/latest-in-trends-hair-and-wigs/index",
                127: "pages/activity/member-birthday",
                128: "pages/activity/member-freetrial",
                129: "pages/activity/member-luck-jackpot",
                130: "pages/activity/member-lucky-draw",
                131: "pages/activity/member-squared-up",
                132: "pages/activity/mixins/setLoading",
                133: "pages/activity/new-arrivals-pop-up",
                134: "pages/activity/new-user",
                135: "pages/activity/pay-1-get-2-wigs/components/pay1get2Product",
                136: "pages/activity/pay-1-get-2-wigs/components/pay1get2ProductCard",
                137: "pages/activity/pay-1-get-2-wigs/index",
                138: "pages/activity/play-claw-machine",
                139: "pages/activity/plus-exclusive",
                140: "pages/activity/pointsauction",
                141: "pages/activity/prize-wheel",
                142: "pages/activity/returncustomer/surveynew",
                143: "pages/activity/salon",
                144: "pages/activity/share-get-free-wigs",
                145: "pages/activity/student-discount",
                146: "pages/activity/unice-2023-annual-report/ReortHead",
                147: "pages/activity/unice-2023-annual-report/ReportPop",
                148: "pages/activity/unice-2023-annual-report/index",
                149: "pages/activity/unice-8th-anniversary-flash-sale",
                150: "pages/activity/unice-8th-anniversary-saving-guide",
                151: "pages/activity/unice-hair-store-grand-opening-event",
                152: "pages/activity/unice-hair-stylist-request",
                153: "pages/activity/unice-queen-show",
                154: "pages/activity/unice-vip-member-activity-gift-card",
                155: "pages/activity/unice-vip-memeber-activity-surprise-box",
                156: "pages/activity/unice-wigs-on-sale",
                157: "pages/activity/unice-x-program",
                158: "pages/activity/vote-for-the-best-black-friday-unice-wig/index",
                159: "pages/blog/_name",
                160: "pages/blog/category/_name",
                161: "pages/blog/index",
                162: "pages/cart/index",
                163: "pages/cart/share-bag",
                164: "pages/contact-us",
                165: "pages/customer/address/addressForm",
                166: "pages/customer/address/components/AddressItem",
                167: "pages/customer/address/index",
                168: "pages/customer/components/cancel-order",
                169: "pages/customer/coupon/index",
                170: "pages/customer/gift/index",
                171: "pages/customer/index",
                172: "pages/customer/order/detail/_id",
                173: "pages/customer/order/index",
                174: "pages/customer/order/return/_type",
                175: "pages/customer/order/return/components/contact-us",
                176: "pages/customer/order/return/components/refund-top",
                177: "pages/customer/order/return/index",
                178: "pages/customer/order/review/_id",
                179: "pages/customer/points/index",
                180: "pages/customer/points/pointDetail",
                181: "pages/customer/setting/changePassword",
                182: "pages/customer/setting/email",
                183: "pages/customer/setting/info",
                184: "pages/customer/setting/name",
                185: "pages/customer/visits/index",
                186: "pages/customer/wallet/index",
                187: "pages/customer/wishlist/index",
                188: "pages/faq/_type",
                189: "pages/faq/components/FaqItem",
                190: "pages/faq/detail/_detail",
                191: "pages/faq/index",
                192: "pages/forgotpassword",
                193: "pages/index",
                194: "pages/intercept",
                195: "pages/login",
                196: "pages/login-loading",
                197: "pages/member/components/joinMember",
                198: "pages/member/index",
                199: "pages/member/plus",
                200: "pages/monitor",
                201: "pages/order/components/ConfirmAddress",
                202: "pages/order/components/GivePlus",
                203: "pages/order/components/ModifyAddress",
                204: "pages/order/confirm",
                205: "pages/order/payWait",
                206: "pages/order/payment",
                207: "pages/order/unpaid",
                208: "pages/qa/_productId",
                209: "pages/qa/components/CategoryQaAnswer",
                210: "pages/qa/components/CategoryQaIndex",
                211: "pages/qa/components/CategoryQaItem",
                212: "pages/qa/components/QaAnswer",
                213: "pages/qa/components/QaIndex",
                214: "pages/register",
                215: "pages/retail-stores/detail",
                216: "pages/retail-stores/index",
                217: "pages/reviews/components/ReviewsItem",
                218: "pages/reviews/components/ReviewsWaterFall",
                219: "pages/reviews/components/ReviewsWaterFallnew",
                220: "pages/reviews/list",
                221: "pages/search/index",
                222: "pages/share-active",
                223: "pages/student-discount",
                224: "pages/topic/components/messageItem",
                225: "pages/topic/detail/_id",
                226: "pages/topic/index",
                227: "pages/topic/search/index",
                228: "pages/track-order/index",
                229: "pages/unice-hair-stylist-arrange/detail",
                230: "pages/unice-hair-stylist-arrange/index",
                231: "pages/unice-rebranding-intro/index",
                232: "pages/wholesale"
            }[e] || e) + ".css?v=1714457399325", c = i.p + p, r = document.getElementsByTagName("link"), m = 0; m < r.length; m++) {
                var g = (u = r[m]).getAttribute("data-href") || u.getAttribute("href");
                if (!("stylesheet" !== u.rel && "preload" !== u.rel || g !== p && g !== c))
                    return n = !0,
                    t()
            }
            var d = document.getElementsByTagName("style");
            for (m = 0; m < d.length; m++) {
                var u;
                if ((g = (u = d[m]).getAttribute("data-href")) === p || g === c)
                    return t()
            }
            var l = document.createElement("link");
            l.rel = o ? "preload" : "stylesheet",
            o ? l.as = "style" : l.type = "text/css",
            l.onload = t,
            l.onerror = function(t) {
                var o = t && t.target && t.target.src || c
                  , n = new Error("Loading CSS chunk " + e + " failed.\n(" + o + ")");
                n.code = "CSS_CHUNK_LOAD_FAILED",
                n.request = o,
                delete s[e],
                l.parentNode.removeChild(l),
                a(n)
            }
            ,
            l.href = c,
            document.getElementsByTagName("head")[0].appendChild(l)
        }
        )).then((function() {
            if (s[e] = 0,
            !n && o) {
                var t = document.createElement("link");
                t.href = i.p + "" + ({
                    0: "pages/reviews/components/ReviewsImgDialog",
                    1: "pages/activity/components/ActivityProduct",
                    2: "components/quick-pay",
                    3: "components/lq-address-form",
                    4: "components/design-components-components-normal-card",
                    5: "components/redeem-product",
                    6: "pages/activity/new-arrivals-pop-up/pages/contact-us/pages/retail-stores/index/pages/share-active/pag/1236ca99",
                    7: "pages/blog/components/BlogLeft",
                    8: "pages/activity/components/ImgClip",
                    9: "pages/customer/order/return/components/order-detail",
                    10: "pages/qa/components/QaItem",
                    11: "components/pay",
                    12: "pages/blog/components/BlogItem",
                    13: "commons/pages/activity/new-user/pages/activity/play-claw-machine",
                    14: "components/canle-order",
                    15: "components/design-components-banner",
                    16: "components/design-components-bannerts",
                    17: "components/design-components-barrages",
                    18: "components/design-components-button",
                    19: "components/design-components-carousel",
                    20: "components/design-components-comment",
                    21: "components/design-components-components-flash-sale-card-amount",
                    22: "components/design-components-components-flash-sale-card-discount",
                    23: "components/design-components-components-four-product-swiper",
                    24: "components/design-components-components-option-card",
                    25: "components/design-components-components-points-card",
                    26: "components/design-components-components-stock-card",
                    27: "components/design-components-count-diy",
                    28: "components/design-components-coupon",
                    29: "components/design-components-cutdowns",
                    30: "components/design-components-elevator-nav",
                    31: "components/design-components-flash-sale-everyday",
                    32: "components/design-components-goods-list",
                    33: "components/design-components-goods-list-tab",
                    34: "components/design-components-image-text",
                    35: "components/design-components-morevideos",
                    36: "components/design-components-questions",
                    37: "components/design-components-recommend-list",
                    38: "components/design-components-rich-text",
                    39: "components/design-components-share",
                    40: "components/design-components-title",
                    41: "components/design-components-videos",
                    42: "components/order-detail",
                    43: "components/point-redeem-coupon",
                    44: "components/product-how-to",
                    45: "components/product-list-filter",
                    46: "components/user-product-list",
                    47: "pages/activity/unice-8th-anniversary-saving-guide/pages/index",
                    48: "pages/cart/GatherProduct",
                    49: "pages/customer/order/return/components/Refund",
                    50: "pages/order/components/GiveUp",
                    53: "components/billing-note",
                    54: "components/bottom-img-list",
                    55: "components/bread-crumb",
                    56: "components/broken-skeleton",
                    57: "components/chat-line",
                    58: "components/cms-page",
                    59: "components/coupon-pop",
                    60: "components/el-select",
                    61: "components/faq",
                    62: "components/five-star",
                    63: "components/head-title",
                    64: "components/home-flash",
                    65: "components/img-upload",
                    66: "components/ios-btn",
                    67: "components/loading-animationpage",
                    68: "components/loading-start",
                    69: "components/lq-check-box",
                    70: "components/lq-track-detail",
                    71: "components/lqwallet",
                    72: "components/min-cart-item",
                    73: "components/multi-select-button",
                    74: "components/need-help",
                    75: "components/order-coupon-item",
                    76: "components/order-use-address",
                    77: "components/order-use-coupon-p-c",
                    78: "components/order-use-email",
                    79: "components/order-use-pay-methods",
                    80: "components/order-use-point",
                    81: "components/pagenation",
                    82: "components/pop-thrid-login-coupon",
                    83: "components/product-card",
                    84: "components/product-detail",
                    85: "components/product-detail-estimated-price",
                    86: "components/product-detail-interests",
                    87: "components/product-gift",
                    88: "components/product-how-to-item",
                    89: "components/product-image",
                    90: "components/product-list",
                    91: "components/product-top",
                    92: "components/radio-button-item",
                    93: "components/review-filter",
                    94: "components/select-option",
                    95: "components/service",
                    96: "components/sitejabber-no",
                    97: "components/slide-bottom-dialog",
                    98: "components/slide-middle-dialog",
                    99: "components/slide-right-dialog",
                    100: "components/slide-top-dialog",
                    101: "components/swiper-diy",
                    102: "components/tab-recommend-product",
                    103: "components/third-login-icon",
                    104: "components/topic-photo",
                    105: "pages/403",
                    106: "pages/404",
                    107: "pages/_",
                    108: "pages/activity/_",
                    109: "pages/activity/back-to-school",
                    110: "pages/activity/bargain/index",
                    111: "pages/activity/black-friday-sale",
                    112: "pages/activity/black-friday-shopping-guide",
                    113: "pages/activity/check-in-get-rewards",
                    114: "pages/activity/components/ActivityPointRedeemCoupon",
                    115: "pages/activity/components/ActivityPointRedeemProduct",
                    116: "pages/activity/components/BarrageSwiper",
                    117: "pages/activity/components/GiftCardRecommendProduct",
                    118: "pages/activity/components/PrizeWheelDialog",
                    119: "pages/activity/components/Upload",
                    120: "pages/activity/components/UploadImgVideo",
                    121: "pages/activity/customer-photo-gallery",
                    122: "pages/activity/customerreview",
                    123: "pages/activity/every-day-flash",
                    124: "pages/activity/halloween",
                    125: "pages/activity/how-to-get-free-hair-and-cash-reward",
                    126: "pages/activity/latest-in-trends-hair-and-wigs/index",
                    127: "pages/activity/member-birthday",
                    128: "pages/activity/member-freetrial",
                    129: "pages/activity/member-luck-jackpot",
                    130: "pages/activity/member-lucky-draw",
                    131: "pages/activity/member-squared-up",
                    132: "pages/activity/mixins/setLoading",
                    133: "pages/activity/new-arrivals-pop-up",
                    134: "pages/activity/new-user",
                    135: "pages/activity/pay-1-get-2-wigs/components/pay1get2Product",
                    136: "pages/activity/pay-1-get-2-wigs/components/pay1get2ProductCard",
                    137: "pages/activity/pay-1-get-2-wigs/index",
                    138: "pages/activity/play-claw-machine",
                    139: "pages/activity/plus-exclusive",
                    140: "pages/activity/pointsauction",
                    141: "pages/activity/prize-wheel",
                    142: "pages/activity/returncustomer/surveynew",
                    143: "pages/activity/salon",
                    144: "pages/activity/share-get-free-wigs",
                    145: "pages/activity/student-discount",
                    146: "pages/activity/unice-2023-annual-report/ReortHead",
                    147: "pages/activity/unice-2023-annual-report/ReportPop",
                    148: "pages/activity/unice-2023-annual-report/index",
                    149: "pages/activity/unice-8th-anniversary-flash-sale",
                    150: "pages/activity/unice-8th-anniversary-saving-guide",
                    151: "pages/activity/unice-hair-store-grand-opening-event",
                    152: "pages/activity/unice-hair-stylist-request",
                    153: "pages/activity/unice-queen-show",
                    154: "pages/activity/unice-vip-member-activity-gift-card",
                    155: "pages/activity/unice-vip-memeber-activity-surprise-box",
                    156: "pages/activity/unice-wigs-on-sale",
                    157: "pages/activity/unice-x-program",
                    158: "pages/activity/vote-for-the-best-black-friday-unice-wig/index",
                    159: "pages/blog/_name",
                    160: "pages/blog/category/_name",
                    161: "pages/blog/index",
                    162: "pages/cart/index",
                    163: "pages/cart/share-bag",
                    164: "pages/contact-us",
                    165: "pages/customer/address/addressForm",
                    166: "pages/customer/address/components/AddressItem",
                    167: "pages/customer/address/index",
                    168: "pages/customer/components/cancel-order",
                    169: "pages/customer/coupon/index",
                    170: "pages/customer/gift/index",
                    171: "pages/customer/index",
                    172: "pages/customer/order/detail/_id",
                    173: "pages/customer/order/index",
                    174: "pages/customer/order/return/_type",
                    175: "pages/customer/order/return/components/contact-us",
                    176: "pages/customer/order/return/components/refund-top",
                    177: "pages/customer/order/return/index",
                    178: "pages/customer/order/review/_id",
                    179: "pages/customer/points/index",
                    180: "pages/customer/points/pointDetail",
                    181: "pages/customer/setting/changePassword",
                    182: "pages/customer/setting/email",
                    183: "pages/customer/setting/info",
                    184: "pages/customer/setting/name",
                    185: "pages/customer/visits/index",
                    186: "pages/customer/wallet/index",
                    187: "pages/customer/wishlist/index",
                    188: "pages/faq/_type",
                    189: "pages/faq/components/FaqItem",
                    190: "pages/faq/detail/_detail",
                    191: "pages/faq/index",
                    192: "pages/forgotpassword",
                    193: "pages/index",
                    194: "pages/intercept",
                    195: "pages/login",
                    196: "pages/login-loading",
                    197: "pages/member/components/joinMember",
                    198: "pages/member/index",
                    199: "pages/member/plus",
                    200: "pages/monitor",
                    201: "pages/order/components/ConfirmAddress",
                    202: "pages/order/components/GivePlus",
                    203: "pages/order/components/ModifyAddress",
                    204: "pages/order/confirm",
                    205: "pages/order/payWait",
                    206: "pages/order/payment",
                    207: "pages/order/unpaid",
                    208: "pages/qa/_productId",
                    209: "pages/qa/components/CategoryQaAnswer",
                    210: "pages/qa/components/CategoryQaIndex",
                    211: "pages/qa/components/CategoryQaItem",
                    212: "pages/qa/components/QaAnswer",
                    213: "pages/qa/components/QaIndex",
                    214: "pages/register",
                    215: "pages/retail-stores/detail",
                    216: "pages/retail-stores/index",
                    217: "pages/reviews/components/ReviewsItem",
                    218: "pages/reviews/components/ReviewsWaterFall",
                    219: "pages/reviews/components/ReviewsWaterFallnew",
                    220: "pages/reviews/list",
                    221: "pages/search/index",
                    222: "pages/share-active",
                    223: "pages/student-discount",
                    224: "pages/topic/components/messageItem",
                    225: "pages/topic/detail/_id",
                    226: "pages/topic/index",
                    227: "pages/topic/search/index",
                    228: "pages/track-order/index",
                    229: "pages/unice-hair-stylist-arrange/detail",
                    230: "pages/unice-hair-stylist-arrange/index",
                    231: "pages/unice-rebranding-intro/index",
                    232: "pages/wholesale"
                }[e] || e) + ".css?v=1714457399325",
                t.rel = "stylesheet",
                t.type = "text/css",
                document.body.appendChild(t)
            }
        }
        )));
        var p = a[e];
        if (0 !== p)
            if (p)
                t.push(p[2]);
            else {
                var c = new Promise((function(t, o) {
                    p = a[e] = [t, o]
                }
                ));
                t.push(p[2] = c);
                var r, m = document.createElement("script");
                m.charset = "utf-8",
                m.timeout = 120,
                i.nc && m.setAttribute("nonce", i.nc),
                m.src = function(e) {
                    return i.p + "" + ({
                        0: "pages/reviews/components/ReviewsImgDialog",
                        1: "pages/activity/components/ActivityProduct",
                        2: "components/quick-pay",
                        3: "components/lq-address-form",
                        4: "components/design-components-components-normal-card",
                        5: "components/redeem-product",
                        6: "pages/activity/new-arrivals-pop-up/pages/contact-us/pages/retail-stores/index/pages/share-active/pag/1236ca99",
                        7: "pages/blog/components/BlogLeft",
                        8: "pages/activity/components/ImgClip",
                        9: "pages/customer/order/return/components/order-detail",
                        10: "pages/qa/components/QaItem",
                        11: "components/pay",
                        12: "pages/blog/components/BlogItem",
                        13: "commons/pages/activity/new-user/pages/activity/play-claw-machine",
                        14: "components/canle-order",
                        15: "components/design-components-banner",
                        16: "components/design-components-bannerts",
                        17: "components/design-components-barrages",
                        18: "components/design-components-button",
                        19: "components/design-components-carousel",
                        20: "components/design-components-comment",
                        21: "components/design-components-components-flash-sale-card-amount",
                        22: "components/design-components-components-flash-sale-card-discount",
                        23: "components/design-components-components-four-product-swiper",
                        24: "components/design-components-components-option-card",
                        25: "components/design-components-components-points-card",
                        26: "components/design-components-components-stock-card",
                        27: "components/design-components-count-diy",
                        28: "components/design-components-coupon",
                        29: "components/design-components-cutdowns",
                        30: "components/design-components-elevator-nav",
                        31: "components/design-components-flash-sale-everyday",
                        32: "components/design-components-goods-list",
                        33: "components/design-components-goods-list-tab",
                        34: "components/design-components-image-text",
                        35: "components/design-components-morevideos",
                        36: "components/design-components-questions",
                        37: "components/design-components-recommend-list",
                        38: "components/design-components-rich-text",
                        39: "components/design-components-share",
                        40: "components/design-components-title",
                        41: "components/design-components-videos",
                        42: "components/order-detail",
                        43: "components/point-redeem-coupon",
                        44: "components/product-how-to",
                        45: "components/product-list-filter",
                        46: "components/user-product-list",
                        47: "pages/activity/unice-8th-anniversary-saving-guide/pages/index",
                        48: "pages/cart/GatherProduct",
                        49: "pages/customer/order/return/components/Refund",
                        50: "pages/order/components/GiveUp",
                        53: "components/billing-note",
                        54: "components/bottom-img-list",
                        55: "components/bread-crumb",
                        56: "components/broken-skeleton",
                        57: "components/chat-line",
                        58: "components/cms-page",
                        59: "components/coupon-pop",
                        60: "components/el-select",
                        61: "components/faq",
                        62: "components/five-star",
                        63: "components/head-title",
                        64: "components/home-flash",
                        65: "components/img-upload",
                        66: "components/ios-btn",
                        67: "components/loading-animationpage",
                        68: "components/loading-start",
                        69: "components/lq-check-box",
                        70: "components/lq-track-detail",
                        71: "components/lqwallet",
                        72: "components/min-cart-item",
                        73: "components/multi-select-button",
                        74: "components/need-help",
                        75: "components/order-coupon-item",
                        76: "components/order-use-address",
                        77: "components/order-use-coupon-p-c",
                        78: "components/order-use-email",
                        79: "components/order-use-pay-methods",
                        80: "components/order-use-point",
                        81: "components/pagenation",
                        82: "components/pop-thrid-login-coupon",
                        83: "components/product-card",
                        84: "components/product-detail",
                        85: "components/product-detail-estimated-price",
                        86: "components/product-detail-interests",
                        87: "components/product-gift",
                        88: "components/product-how-to-item",
                        89: "components/product-image",
                        90: "components/product-list",
                        91: "components/product-top",
                        92: "components/radio-button-item",
                        93: "components/review-filter",
                        94: "components/select-option",
                        95: "components/service",
                        96: "components/sitejabber-no",
                        97: "components/slide-bottom-dialog",
                        98: "components/slide-middle-dialog",
                        99: "components/slide-right-dialog",
                        100: "components/slide-top-dialog",
                        101: "components/swiper-diy",
                        102: "components/tab-recommend-product",
                        103: "components/third-login-icon",
                        104: "components/topic-photo",
                        105: "pages/403",
                        106: "pages/404",
                        107: "pages/_",
                        108: "pages/activity/_",
                        109: "pages/activity/back-to-school",
                        110: "pages/activity/bargain/index",
                        111: "pages/activity/black-friday-sale",
                        112: "pages/activity/black-friday-shopping-guide",
                        113: "pages/activity/check-in-get-rewards",
                        114: "pages/activity/components/ActivityPointRedeemCoupon",
                        115: "pages/activity/components/ActivityPointRedeemProduct",
                        116: "pages/activity/components/BarrageSwiper",
                        117: "pages/activity/components/GiftCardRecommendProduct",
                        118: "pages/activity/components/PrizeWheelDialog",
                        119: "pages/activity/components/Upload",
                        120: "pages/activity/components/UploadImgVideo",
                        121: "pages/activity/customer-photo-gallery",
                        122: "pages/activity/customerreview",
                        123: "pages/activity/every-day-flash",
                        124: "pages/activity/halloween",
                        125: "pages/activity/how-to-get-free-hair-and-cash-reward",
                        126: "pages/activity/latest-in-trends-hair-and-wigs/index",
                        127: "pages/activity/member-birthday",
                        128: "pages/activity/member-freetrial",
                        129: "pages/activity/member-luck-jackpot",
                        130: "pages/activity/member-lucky-draw",
                        131: "pages/activity/member-squared-up",
                        132: "pages/activity/mixins/setLoading",
                        133: "pages/activity/new-arrivals-pop-up",
                        134: "pages/activity/new-user",
                        135: "pages/activity/pay-1-get-2-wigs/components/pay1get2Product",
                        136: "pages/activity/pay-1-get-2-wigs/components/pay1get2ProductCard",
                        137: "pages/activity/pay-1-get-2-wigs/index",
                        138: "pages/activity/play-claw-machine",
                        139: "pages/activity/plus-exclusive",
                        140: "pages/activity/pointsauction",
                        141: "pages/activity/prize-wheel",
                        142: "pages/activity/returncustomer/surveynew",
                        143: "pages/activity/salon",
                        144: "pages/activity/share-get-free-wigs",
                        145: "pages/activity/student-discount",
                        146: "pages/activity/unice-2023-annual-report/ReortHead",
                        147: "pages/activity/unice-2023-annual-report/ReportPop",
                        148: "pages/activity/unice-2023-annual-report/index",
                        149: "pages/activity/unice-8th-anniversary-flash-sale",
                        150: "pages/activity/unice-8th-anniversary-saving-guide",
                        151: "pages/activity/unice-hair-store-grand-opening-event",
                        152: "pages/activity/unice-hair-stylist-request",
                        153: "pages/activity/unice-queen-show",
                        154: "pages/activity/unice-vip-member-activity-gift-card",
                        155: "pages/activity/unice-vip-memeber-activity-surprise-box",
                        156: "pages/activity/unice-wigs-on-sale",
                        157: "pages/activity/unice-x-program",
                        158: "pages/activity/vote-for-the-best-black-friday-unice-wig/index",
                        159: "pages/blog/_name",
                        160: "pages/blog/category/_name",
                        161: "pages/blog/index",
                        162: "pages/cart/index",
                        163: "pages/cart/share-bag",
                        164: "pages/contact-us",
                        165: "pages/customer/address/addressForm",
                        166: "pages/customer/address/components/AddressItem",
                        167: "pages/customer/address/index",
                        168: "pages/customer/components/cancel-order",
                        169: "pages/customer/coupon/index",
                        170: "pages/customer/gift/index",
                        171: "pages/customer/index",
                        172: "pages/customer/order/detail/_id",
                        173: "pages/customer/order/index",
                        174: "pages/customer/order/return/_type",
                        175: "pages/customer/order/return/components/contact-us",
                        176: "pages/customer/order/return/components/refund-top",
                        177: "pages/customer/order/return/index",
                        178: "pages/customer/order/review/_id",
                        179: "pages/customer/points/index",
                        180: "pages/customer/points/pointDetail",
                        181: "pages/customer/setting/changePassword",
                        182: "pages/customer/setting/email",
                        183: "pages/customer/setting/info",
                        184: "pages/customer/setting/name",
                        185: "pages/customer/visits/index",
                        186: "pages/customer/wallet/index",
                        187: "pages/customer/wishlist/index",
                        188: "pages/faq/_type",
                        189: "pages/faq/components/FaqItem",
                        190: "pages/faq/detail/_detail",
                        191: "pages/faq/index",
                        192: "pages/forgotpassword",
                        193: "pages/index",
                        194: "pages/intercept",
                        195: "pages/login",
                        196: "pages/login-loading",
                        197: "pages/member/components/joinMember",
                        198: "pages/member/index",
                        199: "pages/member/plus",
                        200: "pages/monitor",
                        201: "pages/order/components/ConfirmAddress",
                        202: "pages/order/components/GivePlus",
                        203: "pages/order/components/ModifyAddress",
                        204: "pages/order/confirm",
                        205: "pages/order/payWait",
                        206: "pages/order/payment",
                        207: "pages/order/unpaid",
                        208: "pages/qa/_productId",
                        209: "pages/qa/components/CategoryQaAnswer",
                        210: "pages/qa/components/CategoryQaIndex",
                        211: "pages/qa/components/CategoryQaItem",
                        212: "pages/qa/components/QaAnswer",
                        213: "pages/qa/components/QaIndex",
                        214: "pages/register",
                        215: "pages/retail-stores/detail",
                        216: "pages/retail-stores/index",
                        217: "pages/reviews/components/ReviewsItem",
                        218: "pages/reviews/components/ReviewsWaterFall",
                        219: "pages/reviews/components/ReviewsWaterFallnew",
                        220: "pages/reviews/list",
                        221: "pages/search/index",
                        222: "pages/share-active",
                        223: "pages/student-discount",
                        224: "pages/topic/components/messageItem",
                        225: "pages/topic/detail/_id",
                        226: "pages/topic/index",
                        227: "pages/topic/search/index",
                        228: "pages/track-order/index",
                        229: "pages/unice-hair-stylist-arrange/detail",
                        230: "pages/unice-hair-stylist-arrange/index",
                        231: "pages/unice-rebranding-intro/index",
                        232: "pages/wholesale"
                    }[e] || e) + ".js?v=1714457399325"
                }(e);
                var g = new Error;
                r = function(t) {
                    m.onerror = m.onload = null,
                    clearTimeout(d);
                    var o = a[e];
                    if (0 !== o) {
                        if (o) {
                            var n = t && ("load" === t.type ? "missing" : t.type)
                              , s = t && t.target && t.target.src;
                            g.message = "Loading chunk " + e + " failed.\n(" + n + ": " + s + ")",
                            g.name = "ChunkLoadError",
                            g.type = n,
                            g.request = s,
                            o[1](g)
                        }
                        a[e] = void 0
                    }
                }
                ;
                var d = setTimeout((function() {
                    r({
                        type: "timeout",
                        target: m
                    })
                }
                ), 12e4);
                m.onerror = m.onload = r,
                document.head.appendChild(m)
            }
        return Promise.all(t)
    }
    ,
    i.m = e,
    i.c = n,
    i.d = function(e, t, o) {
        i.o(e, t) || Object.defineProperty(e, t, {
            enumerable: !0,
            get: o
        })
    }
    ,
    i.r = function(e) {
        "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, {
            value: "Module"
        }),
        Object.defineProperty(e, "__esModule", {
            value: !0
        })
    }
    ,
    i.t = function(e, t) {
        if (1 & t && (e = i(e)),
        8 & t)
            return e;
        if (4 & t && "object" == typeof e && e && e.__esModule)
            return e;
        var o = Object.create(null);
        if (i.r(o),
        Object.defineProperty(o, "default", {
            enumerable: !0,
            value: e
        }),
        2 & t && "string" != typeof e)
            for (var n in e)
                i.d(o, n, function(t) {
                    return e[t]
                }
                .bind(null, n));
        return o
    }
    ,
    i.n = function(e) {
        var t = e && e.__esModule ? function() {
            return e.default
        }
        : function() {
            return e
        }
        ;
        return i.d(t, "a", t),
        t
    }
    ,
    i.o = function(e, t) {
        return Object.prototype.hasOwnProperty.call(e, t)
    }
    ,
    i.p = "/_nuxt/",
    i.oe = function(e) {
        throw e
    }
    ;
    var c = window.webpackJsonp = window.webpackJsonp || []
      , r = c.push.bind(c);
    c.push = t,
    c = c.slice();
    for (var m = 0; m < c.length; m++)
        t(c[m]);
    var g = r;
    o()
}([]);
